name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Verify
        run: ./gradlew check
      - name: Build
        run: ./gradlew shadowJar
      - name: Publish to GitHub Packages Apache Maven
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
        if:
          success()
